[package]
name = "joker_ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
joker_ptr = { path="../joker_ptr" }
serde = { version = "1", features = ["derive"] }